spring.application.name=fitnexus-backend-api
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/fitnexusdb
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect