spring.application.name=fitnexus-backend-api
server.port=8083

spring.config.import=optional:file:./application-secret.properties

spring.datasource.url=${DB_URL}

spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# serpapi.key=YOUR_SERPAPI_API_KEY
serpapi.key=${SERPAPI_KEY}

gemini.api.key=${GEMINI_API_KEY}
gemini.model=gemini-2.0-flash

# FITNEXUS-ADMIN-2026